name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Run tests
        run: echo "PR checks completed successfully!"
