name: CI workflow

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'

jobs:
  push_pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run sample shell command
        run: echo "The workflow is running on push to main or pull request"

  src-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
