name: Secret Test Workflow

on:
push:

jobs:
  testsec:
    runs-on: ubuntu-latest
    steps:
      - name: Set up conda environment
        uses: actions/checkout@v4
        run: |
          echo "Setting up conda environment..."
          # Add your conda setup commands here

      - name: environment variables
        run: |
          echo "$Devops"
        env:
          Devops: ${{ secrets.SECRET_NAME }}
