name: Secret Test Workflow

on:
push:

jobs:
  testsec:
    runs-on: ubuntu-latest
    steps:
      - name: testing  secrets
        run: |
          echo "$Devops..."

      
          echo "$Devops"
        env:
          Devops: ${{ secrets.SECRET_NAME }}
		  - name: environment variables
        run: |
